language: minimal

dist: xenial
addons:
  apt:
    packages:
    - realpath

jobs:
  include:
   # Libraries
   - stage: "Libraries"
     env:
     - PACKAGE=lib/isl

   - stage: "Libraries"
     env:
     - PACKAGE=lib/usb

   - stage: "Libraries"
     env:
     - PACKAGE=lib/ftdi

   # OpenPower toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=ppc64
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=ppc64
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=ppc64
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=ppc64
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=ppc64

   # or1k toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=or1k

   # rv32 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv32

   # lm32 toolchain - no linux
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=lm32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=lm32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32

   # sh2 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=sh
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=sh
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=sh
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=sh

   # Full Linux musl toolchain using musl-cross-make
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=sh

   # Other tools
   - stage: "Other Tools"
     env:
     - PACKAGE=sdcc

   # Programming Tools
   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/iceprog

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/icefunprog

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/openocd

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/flterm

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/fxload

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/dfu-util

   # Verilog Tools - Bitstream Tool
   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/bit/icestorm

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/bit/prjtrellis

   # Verilog Tools - Synthesis
   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/syn/yosys

   # Verilog Tools - Place and Route
   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/pnr/arachne

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/pnr/nextpnr/ice40

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/pnr/nextpnr/ecp5

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/pnr/nextpnr/generic

#   - stage: "Verilog Tools"
#     env:
#     - PACKAGE=verilog/pnr/vtr                 CONDA_CHANNELS=conda-forge

   # Verilog Tools - Simulation
   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/sim/icarus

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/sim/verilator

matrix:
  allow_failures:
  - env: PACKAGE=vtr CONDA_CHANNELS=conda-forge
  fast_finish: true

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - /home/travis/.conda/pkgs
